### ISSUE TITLE
Loading same set of pokemons

### ISSUE THREAD

**Issue by aashutoshrathi** [mohitkyadav/pokearc#12]
Please fix it

_Type_: Bug

**Comment by CalebKoch** [comment]
I'd be willing to work on this one. 

Would you like it to load the pokemon in order? Or should it be random?

**Comment by garrlker** [comment]
Right now [pagination via offset and limit is broken ](https://pokeapi.co/) in the pokeapi

**Comment by garrlker** [comment]
And that will probably be what is causing your problem, atleast for now.

**Comment by garrlker** [comment]
I've submitted a PR #14
