### ISSUE TITLE
Search is not working

### ISSUE THREAD

**Issue by mohitkyadav** [mohitkyadav/pokearc#7]
The error in console is as following.
``
mohitkyadav.github.io/:1 Mixed Content: The page at 'https://mohitkyadav.github.io/pokearc/' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://pokeapi.co/api/v2/pokemon/1/'. This request has been blocked; the content must be served over HTTPS.
``

**Comment by vincentt117** [comment]
Hi @mohitkyadav , I think the issue might be the page needs to be encrypted with HTTPS. GitHub pages now supports this GitHub pages - https://blog.github.com/2018-05-01-github-pages-custom-domains-https/#configuring-your-domain

Site is pre cool btw

**Comment by pnaika** [comment]
hey @mohitkyadav, I believe you should adjust the backend to allow the requesting origin to the cors.

**Comment by wordythebyrd** [comment]
I am submitting a PR to fix.  Cheers and Happy Hacktoberfest!
